-- Lab 2, do-this
CREATE
    USER kvlinden
    IDENTIFIED BY YOUR_PASSWORD;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE MATERIALIZED VIEW,
    UNLIMITED TABLESPACE,
    CREATE SEQUENCE
    TO kvlinden;